### ISSUE TITLE
Integrate meeting title to URL

### ISSUE THREAD

**Issue by alponet** [noyainrain/meetling#66]

**Comment by noyainrain** [comment]
Good call, thank you! :) This should be easy to implement and I'll come around to it shortly.

If you would like to help out, it should be as simple as adding a `title` property/setter to `micro.UI` (in *micro.js*) which updates `document.title`, and then setting `ui.title` in the `MeetingPage` (in *meetling.js*).

**Comment by noyainrain** [comment]
Having a second look at your feature request, I think I may have miss-read it the first time for #69 (which I just implemented ;) ).

Am I correct that you would like to have a shareable meeting URL like `https://meetling.org/meetings/abcd/working-group-meeting`? Good call again.

There are some other features on the [roadmap](https://github.com/noyainrain/meetling/projects/1) right now, in the meantime I'd be happy to take a pull request :) . To implement this, I guess the route for meetings should take an additional title pattern (which is ignored) and the share notification should append the meeting title to the URL (in `meetling.js`).

**Comment by noyainrain** [comment]
Experimental branch: https://github.com/noyainrain/meetling/tree/url-title
