### ISSUE TITLE
Upgrade to webcomponents.js 2

### ISSUE THREAD

**Issue by noyainrain** [noyainrain/meetling#71]
Upgrade to web components v1 once the [webcomponents polyfill supports customized builtin elements](https://github.com/webcomponents/custom-elements/pull/88), which some of our elements are.

[Some things changed](https://developers.google.com/web/fundamentals/getting-started/primers/customelements) and we need to refactor:

* `document.registerElement -> customElements.define`
* `createdCallback -> constructor` (note https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance)
* `attachedCallback -> connectedCallback`
* `detachedCallback -> disconnectedCallback`

With this, reconsider [Shadow DOM](https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom), using the more lightweight [Shady DOM polyifill](https://github.com/webcomponents/shadydom).

**Comment by noyainrain** [comment]
Experimental branch: https://github.com/noyainrain/meetling/tree/web-components-v1

**Comment by snuggs** [comment]
To be clear this isn't a refactor it's a bonafied feature change @noyainrain

**Comment by noyainrain** [comment]
Dear @snuggs, I'm not sure I get your point, could you please elaborate? :)

**Comment by snuggs** [comment]
Oh bcause of the different API. There were breaking changes to v1 API which is what makes it a "non-refactor". 
![capture d ecran 2017-07-28 a 12 16 56](https://user-images.githubusercontent.com/38223/28726395-1de5575a-738f-11e7-9aac-0e1cbc7b29d4.png)

**Comment by noyainrain** [comment]
Moved to noyainrain/micro#54.
